### ISSUE TITLE
The getter 'coordinate' was called on null. Receiver: null Tried calling: coordinate

### ISSUE THREAD

**Issue by xieyuhai** [fluttify-project/amap_location_fluttify#105]
**插件版本** amap_all_fluttify: 0.15.1

**遇到bug的平台(Android/iOS)** iOS  iphone 8 plus

**描述bug**. 
The getter 'coordinate' was called on null. Receiver: null Tried calling: coordinate

**复现步骤**

**期望行为**

**截图**

**flutter doctor**

**Comment by Antduo** [comment]
I have the same problem on ios 

flutter: The following NoSuchMethodError was thrown:
flutter: The getter 'coordinate' was called on null.
flutter: Receiver: null
flutter: Tried calling: coordinate
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
flutter: #1      _Community.fetchLocation.<anonymous closure>.<anonymous closure> (package:amap_location_fluttify/src/facade/amap_location.dart:163:34)
flutter: <asynchronous suspension>
flutter: #2      _Community.fetchLocation.<anonymous closure>.<anonymous closure> (package:amap_location_fluttify/src/facade/amap_location.dart)
flutter: #3      AMapLocationManager.requestLocationWithReGeocode_completionBlock.<anonymous closure> (package:amap_location_fluttify/src/ios/AMapLocationManager.g.dart:391:61)
flutter: #4      MethodChannel._handleAsMethodCall (package:flutter/src/services/platform_channel.dart:430:55)
flutter: #5      MethodChannel.setMethodCallHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:383:34)
flutter: #6      _DefaultBinaryMessenger.handlePlatformMessage (package:flutter/src/services/binding.dart:283:33)
flutter: #7      _invoke3.<anonymous closure> (dart:ui/hooks.dart:280:15)
flutter: #11     _invoke3 (dart:ui/hooks.dart:279:10)
flutter: #12     _dispatchPlatformMessage (dart:ui/hooks.dart:154:5)
flutter: (elided 3 frames from dart:async)
