### ISSUE TITLE
定们没有返回数据 ，但日志里不停地打印位置信息。【快疯了】

### ISSUE THREAD

**Issue by MuZiLee** [fluttify-project/amap_location_fluttify#11]
**插件版本**
amap_location_fluttify: ^0.2.7+d2eb645
**描述bug**
昨天还可以正常使用，今天莫名奇妙一大推页面开始报错。一直没有想到是定位没有数据的问题。直接无意中点击到位置页面结果出来null。是什么原因没有返回位置信息，而日志里都能被打印出来？
**复现步骤**

**期望行为**

**截图**
![image](https://user-images.githubusercontent.com/7467318/69174081-1a92e800-0b3c-11ea-8240-293e522b71bc.png)

![image](https://user-images.githubusercontent.com/7467318/69174068-1070e980-0b3c-11ea-9dd5-011f7877c793.png)

**flutter doctor**

**Comment by yohom** [comment]
看你debug的信息，`_androidModel`不是有值的吗，不是null啊

**Comment by MuZiLee** [comment]
_androidModel是有值 ，location没有。

**Comment by yohom** [comment]
昨天还有用，最近几天也没有更新过，会不会是你把定位关掉了？

**Comment by MuZiLee** [comment]
所有设备都一样。fluttify-java-callback: onLocationChanged有返回数据。没有回调给locationChanged

**Comment by BoyYangyang** [comment]
看下你的jks是不是用的测试环境的,注册appkey的jks是正式环境的

**Comment by MuZiLee** [comment]
@BoyYangyang 我还没有到打包环节。还在debug模式开发。另外正式环境的jks如何创建？

**Comment by BoyYangyang** [comment]
@MuZiLee debug环境的jks默认在.android包里,你在高德上注册的sh1应该用的是生产环境的jks吧?

**Comment by BoyYangyang** [comment]
@MuZiLee jks就是签名文件呀

**Comment by MuZiLee** [comment]
没办法，后来换库了。
