### ISSUE TITLE
Unhandled Exception: PlatformException(***确保调用SDK任何接口前先调用更新隐私合规updatePrivacyShow、updatePrivacyAgree两个接口并且参数值都为true，若未正确设置有崩溃风险*** E/flutter (28861): 使用loc SDK 功能前请设置隐私权政策是否弹窗告知用户, null, null, null)

### ISSUE THREAD

**Issue by wangyan-png** [fluttify-project/amap_location_fluttify#110]
**插件版本**   0.20.0

**遇到bug的平台(Android/iOS)**  Android

**描述bug**  Unhandled Exception: PlatformException(***确保调用SDK任何接口前先调用更新隐私合规updatePrivacyShow、updatePrivacyAgree两个接口并且参数值都为true，若未正确设置有崩溃风险*** E/flutter (28861): 使用loc SDK 功能前请设置隐私权政策是否弹窗告知用户, null, null, null)

**复现步骤**  安卓无法定位

**期望行为**

**截图**
![image](https://user-images.githubusercontent.com/57902728/139794267-c0062dd8-9fe1-407e-98ed-4808bd13187b.png)

**flutter doctor**
![image](https://user-images.githubusercontent.com/57902728/139794213-9600a346-89f6-43fc-b454-5221c7112d29.png)

**Comment by qs991011** [comment]
我也遇到了，貌似flutter插件暂时不能用最新的定位sdk，把定位的版本改到5.5.1就能用了，[官方说明](https://lbs.amap.com/news/sdkhgsy)

**Comment by shaoting0730** [comment]
@qs991011  最高的有5.5.1 么？？？

**Comment by qs991011** [comment]
> @qs991011 最高的有5.5.1 么？？？

安卓定位sdk的版本

**Comment by shaoting0730** [comment]
@qs991011  你的意思是flutter里面改用安卓的定位？？

**Comment by qs991011** [comment]
> @qs991011 你的意思是flutter里面改用安卓的定位？？

flutter插件要引用sdk包，gradle项目不导入sdk，安卓应用的定位功能是不能用的，高德flutter插件的的官方文档说的很清楚。

**Comment by shaoting0730** [comment]
@qs991011 这样啊。意思是不需要啥写一个界面弹出来给用户点击那种，直接配置Android 原生工程的sdk就行。谢谢。44

**Comment by qs991011** [comment]
@pheromone  直接用

**Comment by shaoting0730** [comment]
@qs991011  是5.5.1
![image](https://user-images.githubusercontent.com/14305431/147316455-8761a0da-c689-4038-9ec5-5d1d1aabd7ed.png)

**Comment by qs991011** [comment]
> @pheromone 地图包也要换

**Comment by shaoting0730** [comment]
https://blog.csdn.net/qq_42772570/article/details/121512640 这样就行，其实不用换
