### ISSUE TITLE
安卓编译失败

### ISSUE THREAD

**Issue by lyricdon** [fluttify-project/amap_location_fluttify#112]
**插件版本**
0.21.0-dev.0

**遇到bug的平台(Android/iOS)**
安卓

**描述bug**
编译失败

**截图**
![16281644810787_ pic](https://user-images.githubusercontent.com/12814752/153797778-65c01bdb-5800-4e27-a8fe-78e6cb2dd1f8.jpg)

**Comment by chaochaox1990** [comment]
+1

**Comment by huodoushigemi** [comment]
+1

**Comment by huodoushigemi** [comment]
> **插件版本** 0.21.0-dev.0
> 
> **遇到bug的平台(Android/iOS)** 安卓
> 
> **描述bug** 编译失败
> 
> **截图** ![16281644810787_ pic](https://user-images.githubusercontent.com/12814752/153797778-65c01bdb-5800-4e27-a8fe-78e6cb2dd1f8.jpg)

请问这个解决了吗？

**Comment by g707175425** [comment]
+1
