### ISSUE TITLE
ios依赖冲突

### ISSUE THREAD

**Issue by lxbestno1** [fluttify-project/amap_location_fluttify#113]
之前项目中使用了amap_flutter_map，添加amap_location_fluttify后ios pod install 报错： The 'Pods-Runner' target has frameworks with conflicting names: amapfoundationkit.framework

**Comment by gaoyueban** [comment]
老哥解决了吗？我现在碰到相同的问题了。

**Comment by lxbestno1** [comment]
没有使用amap_location_fluttify了，定位用amap_flutter_location

**Comment by gaoyueban** [comment]
那你的后台定位是怎么解决的？
&nbsp;


2662234579
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年2月27日(星期一) 下午5:47
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [fluttify-project/amap_location_fluttify] ios依赖冲突 (Issue #113)





 
没有使用amap_location_fluttify了，定位用amap_flutter_location

**Comment by lxbestno1** [comment]
没有后台定位这个需求，就是简单的即时定位...主要我不太熟ios，上面那个错查了一些资料搞不定，就放弃了

**Comment by gaoyueban** [comment]
好吧。&nbsp;


2662234579
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年2月27日(星期一) 下午5:54
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [fluttify-project/amap_location_fluttify] ios依赖冲突 (Issue #113)





 
没有后台定位这个需求，就是简单的即时定位...主要我不太熟ios，上面那个错查了一些资料搞不定，就放弃了
