### ISSUE TITLE
ios定位很慢，android速度很快

### ISSUE THREAD

**Issue by pan365wang** [fluttify-project/amap_location_fluttify#12]
ios定位很慢，甚至感觉超过2秒，android速度很快几乎实时拿到。

**Comment by pan365wang** [comment]
0.2.7+d2eb645

**Comment by pan365wang** [comment]
@yshye @yohom

**Comment by yohom** [comment]
这个是平台限制，插件做不了什么优化。你看下高德官方的文档 https://lbs.amap.com/api/ios-location-sdk/guide/get-location/singlelocation

**Comment by pan365wang** [comment]
那么这样，我每次去单次拿的方式可能行不通。实在太慢。连续定位能设置时间间隔吗？或者现在的间隔是多少
