### ISSUE TITLE
使用location.altitude拿不到海拔

### ISSUE THREAD

**Issue by BABAICAI** [fluttify-project/amap_location_fluttify#13]
**插件版本**
0.2.7
**描述bug**
使用location.altitude拿不到海拔
**复现步骤**
调用locationChanged: (location) async{};方法,只拿到了经纬度,没有海拔
**期望行为**
可以获取海拔
**截图**
**flutter doctor**

**Comment by yohom** [comment]
android还是ios？

**Comment by yohom** [comment]
如果设备没有移动，海拔也会为0，参考https://lbs.amap.com/faq/android/location-sdk/position/43281。如果能查到其他资料的可以Reopen。
