### ISSUE TITLE
安卓8以上后台定位功能

### ISSUE THREAD

**Issue by JeasonLaung** [fluttify-project/amap_location_fluttify#14]
**功能描述**
安卓8以上后台定位功能
**Native端对应字段/方法**
AMapLocationClient.disableBackgroundLocation(boolean removeNotification)
AMapLocationClient.enableBackgroundLocation(int notificationId, Notification notification)
源码的amap的location sdk示例有（在/app/src/main/java/com/amap/location/demo/Location_BackGround_Activity.java中）
![image](https://user-images.githubusercontent.com/44773434/69607773-f154e900-1060-11ea-919a-89b035bb46df.png)
参考文档：http://amappc.cn-hangzhou.oss-pub.aliyun-inc.com/lbs/static/unzip/Android_Location_Doc/index.html

谢谢大佬！！

**Comment by yohom** [comment]
`Notification`从哪里拿？

**Comment by JeasonLaung** [comment]
直接用app的通知即可

import android.app.Notification;
import android.app.NotificationChannel;
import android.app.NotificationManager;
import android.content.Context;
import android.graphics.Color;


函数代码 https://lbs.amap.com/api/android-location-sdk/guide/utilities/permision_8

Utils.getAppName函数为这个
/**
	 * 获取app的名称
	 * @param context
	 * @return
	 */
	public static String getAppName(Context context) {
		String appName = "";
		try {
			PackageManager packageManager = context.getPackageManager();
			PackageInfo packageInfo = packageManager.getPackageInfo(
					context.getPackageName(), 0);
			int labelRes = packageInfo.applicationInfo.labelRes;
			appName =  context.getResources().getString(labelRes);
		} catch (Throwable e) {
			e.printStackTrace();
		}
		return appName;
	}

**Comment by yohom** [comment]
你这个基本上都是调用的系统API啊，建议你还是fork一份去自己在原生代码里加吧

**Comment by JeasonLaung** [comment]
主要是没写过安卓机呀😅，复制进去改也全是报错，我在试试吧，谢谢大佬
