### ISSUE TITLE
高德IOS定位慢

### ISSUE THREAD

**Issue by king163** [fluttify-project/amap_location_fluttify#16]
**插件版本**
0.3.0+8cf796c
**描述bug**
ios定位慢 市区5~10s才能返回定位地址
**复现步骤**
AmapLocation.startLocation单次定位
**期望行为**
定位返回快，或者可以提供接口只返回经纬度 节约获取地址的时间
**截图**

**flutter doctor**

**Comment by yohom** [comment]
这个参考下[高德官网的描述](https://lbs.amap.com/api/ios-location-sdk/guide/get-location/singlelocation)，插件做不了什么优化。

**Comment by mojinglml** [comment]
定位精度Best改成HundredMeters，定位结果相差不大，但是单次定位快很多
