### ISSUE TITLE
在ios11及以上版本使用example重的授权方式，无法获取权限

### ISSUE THREAD

**Issue by lpfasd123** [fluttify-project/amap_location_fluttify#18]
**插件版本**
amap_core_fluttify: ^0.2.1+97873c8
  permission_handler: ^4.0.0
**遇到bug的平台(Android/iOS)**
ios11
**描述bug**
卡在这里,无返回
```
await PermissionHandler().requestPermissions([PermissionGroup.location, PermissionGroup.locationAlways]);
```
**期望行为**
是否有替代手段

**Comment by yohom** [comment]
你plist中权限配置了吗

**Comment by lpfasd123** [comment]
设置了
```
<key>NSLocationAlwaysUsageDescription</key>
    <string>提供天翼预报的必要组件</string>
    <key>NSLocationWhenInUseUsageDescription</key>
    <string>提供天翼预报的必要组件</string>
```

**Comment by lpfasd123** [comment]
[Request location permission on iOS 11 and above](https://github.com/Baseflow/flutter-permission-handler/issues/161)

**Comment by yohom** [comment]
example工程能正常运行吗

**Comment by lpfasd123** [comment]
不能运行

**Comment by yohom** [comment]
有没有日志？

**Comment by lpfasd123** [comment]
[requestPermission does not return result ](https://github.com/Baseflow/flutter-permission-handler/issues/84)

**Comment by yohom** [comment]
老铁，严格来说这并不属于定位插件的issue啊😂

**Comment by lpfasd123** [comment]
是的，只是希望这个项目有什么替代的方案，来解决这个问题

**Comment by yohom** [comment]
看看有没有别的权限申请的库，这个我也没什么办法
