### ISSUE TITLE
Google Play 被下架

### ISSUE THREAD

**Issue by LunaGao** [fluttify-project/amap_location_fluttify#22]
**插件版本**
0.4.1+82a2243
**遇到bug的平台(Android/iOS)**
Android
**描述bug**
Google Play 被下架
**Google 邮件内容**
> Hi Developers at **_XXXX_**,
>
>After a recent review, T Two, **_your.package.name_** (Version Code 23), has been removed from Google Play due to a policy violation. This app won’t be available to users until you submit a compliant update.
>
>Issue: Violation of Malicious Behavior policy
>
>An app distributed via Google Play may not modify, replace, or update itself using any method other than Google Play's update mechanism. Likewise, an app may not download executable code (e.g. dex, JAR, .so files) from a source other than Google Play.
>
>We found that your app is using a non-compliant version of the **AMAP SDK** which contains code to download executable code (e.g. dex, JAR, .so files) from a source other than Google Play. If necessary, you can consult your SDK provider(s) for further information.
>
>Next steps: Submit your updated app for another review
>
>Read through the Malicious Behavior policy for more details.
Make changes to bring your app into compliance. Be sure to address the issue identified above. In addition to your Production release, if you have other release types that you use for testing and/or quality assurance checks (e.g. Internal test, Closed, Open), please make sure to update those tracks as well.
>Check that your app is compliant with all other Developer Program Policies. Additional enforcement could occur if there are further policy violations.
>Sign in to your Play Console and submit the policy compliant update.
You may also be interested in exploring Dynamic Delivery as an alternative implementation.
>
>If approved, your app will again be available with all installs, ratings, and reviews intact.
>
>If you’ve reviewed the policy and feel this decision may have been in error, please reach out to our policy support team. We’ll get back to you within 2 business days.
>
>Please help us improve the developer experience by completing this two question survey.
>
>Regards,
>
>The Google Play Team

**也许可行的解决方法**
https://ask.dcloud.net.cn/question/80005
作者可以帮忙确认一下高德sdk的版本吗？
谢谢

**Comment by yohom** [comment]
那就是升级一下SDK就可以了吗

**Comment by yohom** [comment]
我在高德官网发现了Google Play的特供版，我开个分支处理一下吧

**Comment by yohom** [comment]
新增了`feature/google-play`分支，处理这个问题。你依赖下这个分支吧。

**Comment by LunaGao** [comment]
@yohom 
感谢感谢，我昨天从新依赖了最新的5.x.x的包，已经重新上传了，如果又被下架了可以试试这个新的分支。

**Comment by KerwinZheng** [comment]
> @yohom
> 感谢感谢，我昨天从新依赖了最新的5.x.x的包，已经重新上传了，如果又被下架了可以试试这个新的分支。

请问审核通过了吗

**Comment by LunaGao** [comment]
> > @yohom
> > 感谢感谢，我昨天从新依赖了最新的5.x.x的包，已经重新上传了，如果又被下架了可以试试这个新的分支。
> 
> 请问审核通过了吗

 @KerwinZheng  审核通过了。使用 `feature/google-play` 才可以。最新的5.x.x的包是不行的。
