### ISSUE TITLE
经度纬度无法获取,报错MissingPluginException(No implementation found for method CLLocation::get_coordinate on channel com.fluttify/foundation_method)

### ISSUE THREAD

**Issue by AstrayV** [fluttify-project/amap_location_fluttify#24]
**插件版本**
amap_location_fluttify: ^0.5.1+a918944
**遇到bug的平台(Android/iOS)**
ios
**描述bug**
await location.latLng 报错
**复现步骤**
  void init() async{
    if(await requestPermission()){
      Location location = await AmapLocation.fetchLocation(needAddress: true);
      print(await location.city);
      try{
        LatLng latLng = await location.latLng;
        print(latLng.latitude);
      }catch(e){
        print(e);
      }
    }
  }

控制台打印:
flutter: fluttify-dart: AMapLocationManager@10739597312::requestLocationWithReGeocode(['withReGeocode':true])
flutter: 深圳市
flutter: MissingPluginException(No implementation found for method CLLocation::get_coordinate on channel com.fluttify/foundation_method)
**期望行为**
正确获取经度纬度
**截图**

**flutter doctor**
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.14.6 18G95,
    locale zh-Hans-CN)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
[✓] Android Studio (version 3.5)
[!] IntelliJ IDEA Ultimate Edition (version 2018.1.7)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.40.2)
[✓] Connected device (1 available)

**Comment by yohom** [comment]
跑一下`flutter packages upgrade`，升级一下底层的`foundation_fluttify`.
