### ISSUE TITLE
升级flutter version v1.12.13和 amap_location_fluttify: "0.5.1+a918944"后debug编译时报错

### ISSUE THREAD

**Issue by mzF414** [fluttify-project/amap_location_fluttify#25]
flutter version v1.12.13+hotfix.6
  amap_core_fluttify:
    version: "0.2.4+bb1f005"
  amap_location_fluttify:
    version: "0.5.1+a918944"

平台(Android)

描述bug
* What went wrong:
Execution failed for task ':app:preDebugBuild'.
> Android dependency 'androidx.fragment:fragment' has different version for the compile (1.0.0-rc01) and runtime (1.0.0) classpath. You should manually set the same version via DependencyResolution

* Where:
Build file 'C:\src\flutter\.pub-cache\hosted\pub.flutter-io.cn\amap_core_fluttify-0.2.4+bb1f005\android\build.gradle' line: 47

* What went wrong:
A problem occurred evaluating root project 'amap_core_fluttify'.
> Cannot convert a null value to an object of type Dependency.
  The following types/formats are supported:
    - Instances of Dependency.
    - String or CharSequence values, for example 'org.gradle:gradle-core:1.0'.
    - Maps, for example [group: 'org.gradle', name: 'gradle-core', version: '1.0'].
    - FileCollections, for example files('some.jar', 'someOther.jar').
    - Projects, for example project(':some:project:path').
    - ClassPathNotation, for example gradleApi().

复现步骤
 升级flutter version v1.12.13和 amap_location_fluttify: "0.5.1+a918944"后debug编译时报错

flutter doctor :
[√] Flutter (Channel unknown, v1.12.13+hotfix.6, on Microsoft Windows [Version 10.0.18362.476], locale zh-CN)

[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[!] Android Studio (version 3.2)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[√] IntelliJ IDEA Ultimate Edition (version 2019.1)
[√] Connected device (1 available)

! Doctor found issues in 2 categories.

**Comment by yohom** [comment]
升级一下kotlin版本到1.3.30和android的gradle插件版本到3.3.1。

**Comment by mzF414** [comment]
谢谢, 已解决

**Comment by zhangruiyu** [comment]
0-0希望能升到到3.5.0啊
