### ISSUE TITLE
Android 运行demo 获取不到经纬度，ios可以获取

### ISSUE THREAD

**Issue by luckmlc** [fluttify-project/amap_location_fluttify#28]
看 AndroidManifest.xml 已经配置了 com.amap.api.v2.apikey
```
<meta-data android:name="com.amap.api.v2.apikey" android:value="20fc807ea4f290d75eae1a7e990588c3"/>
```

结果如图：
![image](https://user-images.githubusercontent.com/48781697/71061134-599b7400-21a2-11ea-97e8-24d0c8b45e07.png)

**Comment by wj1234** [comment]
大佬，请问怎么解决的

**Comment by luckmlc** [comment]
> 大佬，请问怎么解决的

是我的问题，andriod, ios 的apikey不一样，我写错了

**Comment by wj1234** [comment]
哦，谢谢

**Comment by azhanglongfei** [comment]
demo android更新了key，android还是获取不到位置
