### ISSUE TITLE
Location数据以future的方式很麻烦，能不能正常点的

### ISSUE THREAD

**Issue by tygm** [fluttify-project/amap_location_fluttify#31]
从base_location迁移过来（前者在flutter新sdk下有问题），代码改动很麻烦

**Comment by yohom** [comment]
你可以用0.2.x版本，是回调形式的。

**Comment by tygm** [comment]
直接点语法的不是更方便吗，我看了源码是因为要判断平台所以用了future，那可以返回个完整的也好啊，比如isIos,返回整个IOS的location数据，而不是adress/cityCode等一个一个取

**Comment by yohom** [comment]
返回Future的方法都用await修饰就行了
