### ISSUE TITLE
AmapLocation.fetchLocation  限制获取一次问题

### ISSUE THREAD

**Issue by yuefeng007** [fluttify-project/amap_location_fluttify#33]
**插件版本**
 amap_location_fluttify: ^0.7.0+5a112a2
**遇到bug的平台(Android/iOS)**
Android
**描述bug**
AmapLocation.fetchLocation  app安装后仅首次获取有效

杀死app进程后，再进入app 调用方法 依然无效

**期望行为**
个人认为
  AmapLocation.fetchLocation  这个获取一次   应该是 一个app生命周期内的一次。
不应该是 仅首次获取有效
这个方法

**Comment by yuefeng007** [comment]
控制台输出

I/flutter (16677): fluttify-dart: com.amap.api.location.AMapLocationClientOption@12986330::setOnceLocation(['var1':true])
I/flutter (16677): fluttify-dart: com.amap.api.location.AMapLocationClientOption@18846731::setOnceLocation(['var1':true])
I/flutter (16677): fluttify-dart: com.amap.api.location.AMapLocationClientOption@12986330::setLocationMode([])
I/flutter (16677): fluttify-dart: com.amap.api.location.AMapLocationClientOption@18846731::setLocationMode([])
I/flutter (16677): fluttify-dart: com.amap.api.location.AMapLocationClientOption@12986330::setSensorEnable(['var1':true])
I/flutter (16677): fluttify-dart: com.amap.api.location.AMapLocationClientOption@18846731::setSensorEnable(['var1':true])
I/flutter (16677): fluttify-dart: com.amap.api.location.AMapLocationClient@248118673::setLocationOption([])
I/flutter (16677): fluttify-dart: com.amap.api.location.AMapLocationClient@248118673::setLocationOption([])
I/flutter (16677): fluttify-dart: com.amap.api.location.AMapLocationClient@248118673::startLocation([])
I/flutter (16677): fluttify-dart: com.amap.api.location.AMapLocationClient@248118673::startLocation([])

**Comment by yuefeng007** [comment]
我现在用的 0.4.0的版本 是正常的。 在 0.4.x之后就不行了  。取不到   无返回

**Comment by yuefeng007** [comment]
想问下作者，，这个是我个人的原因吗

**Comment by yohom** [comment]
你试下example工程是能够获取到的吗

**Comment by yuefeng007** [comment]
我试了example  确实可以正常获取。因为一些基础配置 就是按0.4.0版本配置的。。到高版本以后我不知道该去改什么地方。这很尴尬。我在试试吧 。应该是我的问题

**Comment by yuefeng007** [comment]
可以看到控制台输出   比正常情况  多了  'var1':true   这个参数

**Comment by yuefeng007** [comment]
找到原因了 。。如果我没有等待上一个请求完成，这时再请求位置信息。。那么以后，我就再也请求不到返回结果了

**Comment by yuefeng007** [comment]
建议这块优化一下，屏蔽重复请求即可。不要像现在这样 永远都请求不到。
