### ISSUE TITLE
建议项目进行升级。

### ISSUE THREAD

**Issue by hqwlkj** [fluttify-project/amap_location_fluttify#34]
**功能描述**

建议项目进行升级。

**Native端对应字段/方法**

现在编译的时候提示 是用了一些过时的 api 

`注: /usr/local/flutter/.pub-cache/hosted/pub.dartlang.org/amap_lcation_fluttify-0.5.1+a918944/android/src/main/java/me/yohom/amap_location_fluttify/AmapLocationFluttifyPlugin.java使用或覆盖了已过时的 API。

注: 有关详细信息, 请使用 -Xlint:deprecation 重新编译。                                                             
注: /usr/local/flutter/.pub-cache/hosted/pub.dartlang.org/amap_location_fluttify-0.5.1+a918944/android/src/main/java/me/yohom/amap_location_fluttify/AmapLocationFluttifyPlugi.java使用了未经检查或不安全的操作。

注: 有关详细信息, 请使用 -Xlint:unchecked 重新编译。`

**Comment by yohom** [comment]
`0.8.1`已经适配了新的android embedding.
