### ISSUE TITLE
pod install的时候报这个错误

### ISSUE THREAD

**Issue by hqwlkj** [fluttify-project/amap_location_fluttify#35]
**插件版本**
`amap_location_fluttify: ^0.8.0+ea37ae9`
**遇到bug的平台(Android/iOS)**

ios

**描述bug**
`Error output from CocoaPods:
↳

    [!] 'AMapFoundation' uses the unencrypted 'http' protocol to transfer the Pod. Please be sure you're in a safe network with only trusted hosts. Otherwise, please reach out to the library author to notify them of this security issue.

Error running pod install
Error launching application on iPhone 11 Pro Max.
`
**复现步骤**

**期望行为**

**截图**
![image](https://user-images.githubusercontent.com/12181423/71442394-9cc88a80-2740-11ea-87ac-8ae328ea9863.png)

**flutter doctor**
`
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.15.2 19C57, locale zh-Hans-CN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
[✓] Android Studio (version 3.5)
[✓] IntelliJ IDEA Ultimate Edition (version 2019.3.1)
[✓] VS Code (version 1.39.2)
[✓] Connected device (2 available)

• No issues found!

`

**Comment by hqwlkj** [comment]
网上查了一些处理方式 
https://github.com/OpenFlutter/amap_base_flutter/issues/35

https://github.com/flutter/flutter/issues/14161



但是问题没有根治，项目依然没有跑起来。

**Comment by yohom** [comment]
如果是swift项目的话，先注释掉Podfile里的`use_frameworks!`试一下。

**Comment by hqwlkj** [comment]
注释后不提示上面的错误，提示了其他的。

**Comment by cv0cv0** [comment]
@hqwlkj 解决了吗？

**Comment by hqwlkj** [comment]
@cv0cv0   没有

**Comment by cv0cv0** [comment]
@hqwlkj 我解决了。
https://www.jianshu.com/p/cdde43197edf
按第 9 条。
