### ISSUE TITLE
ios 编译不通过

### ISSUE THREAD

**Issue by djkloop** [fluttify-project/amap_location_fluttify#36]
**插件版本**
```sh
amap_location_fluttify: ^0.8.0+ea37ae9
```
**遇到bug的平台(Android/iOS)**
```sh
# ios
```
**描述bug**
```sh
# _刚装上插件的时候还能编译通过，然后在安卓模拟器上跑了一遍，回来再ios模拟器上跑就不行了...
```
**复现步骤**
```sh
    flutter run
```
**期望行为**
```sh
# 能够编译通过
```
**截图**
![image](https://user-images.githubusercontent.com/21050914/71455758-769efb00-27d1-11ea-935c-1b9d23193f3e.png)

**flutter doctor**
![image](https://user-images.githubusercontent.com/21050914/71455941-25433b80-27d2-11ea-9561-05b2c61c12b2.png)

**Comment by yohom** [comment]
注释掉Podfile里的`use_frameworks!`或者重新创建项目ios选择objc语言。
