### ISSUE TITLE
stopLocation以后重新listenLocation，同一个数据会出现多次。

### ISSUE THREAD

**Issue by RyanYANG52** [fluttify-project/amap_location_fluttify#37]
**^0.8.0+ea37ae9**

**Android**

**测试方法**
example，只打印onLocationChanged的结果，先开一次onLocationChanged，然后stop，再开启一次onLocationChanged，每秒中会打印两次。

https://github.com/fluttify-project/amap_location_fluttify/blob/812d00b3268367919af0016d44d1d4ec423c54c9/lib/src/dart/amap_location.dart#L255

感觉这里`_androidLocationDelegate = null; `并没有释放，
https://github.com/fluttify-project/amap_location_fluttify/blob/812d00b3268367919af0016d44d1d4ec423c54c9/lib/src/dart/amap_location.dart#L167
这里会新建一个，导致同一个Location会触发多次。
加上这句话后`await _androidClient.unRegisterLocationListener(_androidLocationDelegate);`还是没用。我现在只能注释掉`//_androidLocationDelegate = null;`

**Comment by lilizaimu** [comment]
您好 我也遇到了这个问题 请问你现在又解决方法了吗

**Comment by lilizaimu** [comment]
擦 我是用了一个timer来循环单次获取。。。
