### ISSUE TITLE
设置超时时间的参数应该是int 而不是long

### ISSUE THREAD

**Issue by ws4349893** [fluttify-project/amap_location_fluttify#39]
**插件版本**
0.8.1
**遇到bug的平台(Android/iOS)**
Android
**描述bug**
com.amap.api.location.AMapLocationClientOption::setHttpTimeOut 
接收的参数 “var1” 类型应该是 int 而不是 long
在0.8.0 里面解决了这个问题,但是在 0.8.1 又出现这个问题了
**复现步骤**

**期望行为**

**截图**

**flutter doctor**

**Comment by yohom** [comment]
0.8.9版本已处理。
