### ISSUE TITLE
0.8.1编译报错

### ISSUE THREAD

**Issue by yusian** [fluttify-project/amap_location_fluttify#40]
**插件版本**
^0.8.1+865eb83
**遇到bug的平台(Android/iOS)**
Android
**描述bug**
编译报错：
错误: 无法将类 AmapLocationFluttifyPlugin中的构造器 AmapLocationFluttifyPlugin应用到给定类型;
    flutterEngine.getPlugins().add(new me.yohom.amap_location_fluttify.AmapLocationFluttifyPlugin());
                                   ^                                    
  需要: BinaryMessenger                                                 
  找到: 没有参数                                                        
  原因: 实际参数列表和形式参数列表长度不同                              
1 个错误                                                                
                                                                        
FAILURE: Build failed with an exception.                                
                                                                        
* What went wrong:                                                      
Execution failed for task ':app:compileDebugJavaWithJavac'.             
> Compilation failed; see the compiler error output for details.        
                                                                        
* Try:                                                                  
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
                                                                        
* Get more help at https://help.gradle.org   
**复现步骤**

**期望行为**

**截图**

**flutter doctor**

**Comment by yohom** [comment]
`0.8.2`版本试一下。
