### ISSUE TITLE
0.8.0以上版本iOS出现Error running pod install

### ISSUE THREAD

**Issue by caocong1** [fluttify-project/amap_location_fluttify#43]
插件版本0.8.0 0.8.1 0.8.2
编译iOS时报错

>  Launching lib/main.dart on iPhone in debug mode...
> Automatically signing iOS for device deployment using specified development team in Xcode project: MHK5R57ZM4
> Running pod install...
> CocoaPods' output:
> ↳
>       Preparing
> 
>     Analyzing dependencies
> 
>     Inspecting targets to integrate
>       Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)
> 
>     Finding Podfile changes
>       - Flutter
>       - amap_core_fluttify
>       - amap_location_fluttify
>       - flutter_image_compress
>       - flutter_local_notifications
>       - foundation_fluttify
>       - image_picker
>       - permission_handler
>       - shared_preferences
>       - shared_preferences_macos
>       - shared_preferences_web
> 
>     Fetching external sources
>     -> Fetching podspec for `Flutter` from `Flutter`
>     -> Fetching podspec for `amap_core_fluttify` from `.symlinks/plugins/amap_core_fluttify/ios`
>     -> Fetching podspec for `amap_location_fluttify` from `.symlinks/plugins/amap_location_fluttify/ios`
>     -> Fetching podspec for `flutter_image_compress` from `.symlinks/plugins/flutter_image_compress/ios`
>     -> Fetching podspec for `flutter_local_notifications` from `.symlinks/plugins/flutter_local_notifications/ios`
>     -> Fetching podspec for `foundation_fluttify` from `.symlinks/plugins/foundation_fluttify/ios`
>     -> Fetching podspec for `image_picker` from `.symlinks/plugins/image_picker/ios`
>     -> Fetching podspec for `permission_handler` from `.symlinks/plugins/permission_handler/ios`
>     -> Fetching podspec for `shared_preferences` from `.symlinks/plugins/shared_preferences/ios`
>     -> Fetching podspec for `shared_preferences_macos` from `.symlinks/plugins/shared_preferences_macos/ios`
>     -> Fetching podspec for `shared_preferences_web` from `.symlinks/plugins/shared_preferences_web/ios`
> 
>     Resolving dependencies of `Podfile`
>       CDN: trunk Relative path: CocoaPods-version.yml exists! Returning local because checking is only perfomed in repo update
>       CDN: trunk Relative path: all_pods_versions_8_f_f.txt exists! Returning local because checking is only perfomed in repo update
>       CDN: trunk Relative path: Specs/8/f/f/AMapFoundation/1.6.1/AMapFoundation.podspec.json exists! Returning local because checking is only perfomed in repo update
>       CDN: trunk Relative path: all_pods_versions_0_3_9.txt exists! Returning local because checking is only perfomed in repo update
>       CDN: trunk Relative path: Specs/0/3/9/AMapLocation/2.6.4/AMapLocation.podspec.json exists! Returning local because checking is only perfomed in repo update
>       CDN: trunk Relative path: all_pods_versions_5_d_c.txt exists! Returning local because checking is only perfomed in repo update
>       CDN: trunk Relative path: Specs/5/d/c/Mantle/2.1.0/Mantle.podspec.json exists! Returning local because checking is only perfomed in repo update
>       CDN: trunk Relative path: Specs/8/f/f/AMapFoundation/1.6.0/AMapFoundation.podspec.json exists! Returning local because checking is only perfomed in repo update
>       CDN: trunk Relative path: Specs/0/3/9/AMapLocation/2.6.3/AMapLocation.podspec.json exists! Returning local because checking is only perfomed in repo update
>       CDN: trunk Relative path: Specs/8/f/f/AMapFoundation/1.6.1/AMapFoundation.podspec.json exists! Returning local because checking is only perfomed in repo update
>       CDN: trunk Relative path: Specs/8/f/f/AMapFoundation/1.6.0/AMapFoundation.podspec.json exists! Returning local because checking is only perfomed in repo update
>       CDN: trunk Relative path: Specs/8/f/f/AMapFoundation/1.5.9/AMapFoundation.podspec.json exists! Returning local because checking is only perfomed in repo update
>       CDN: trunk Relative path: Specs/8/f/f/AMapFoundation/1.5.8/AMapFoundation.podspec.json exists! Returning local because checking is only perfomed in repo update
>       CDN: trunk Relative path: Specs/8/f/f/AMapFoundation/1.5.7/AMapFoundation.podspec.json exists! Returning local because checking is only perfomed in repo update
>       CDN: trunk Relative path: Specs/8/f/f/AMapFoundation/1.5.6/AMapFoundation.podspec.json exists! Returning local because checking is only perfomed in repo update
>       CDN: trunk Relative path: Specs/8/f/f/AMapFoundation/1.5.5/AMapFoundation.podspec.json exists! Returning local because checking is only perfomed in repo update
>       CDN: trunk Relative path: Specs/8/f/f/AMapFoundation/1.5.4/AMapFoundation.podspec.json exists! Returning local because checking is only perfomed in repo update
>       CDN: trunk Relative path: Specs/8/f/f/AMapFoundation/1.5.3/AMapFoundation.podspec.json exists! Returning local because checking is only perfomed in repo update
>       CDN: trunk Relative path: Specs/8/f/f/AMapFoundation/1.5.2/AMapFoundation.podspec.json exists! Returning local because checking is only perfomed in repo update
>       CDN: trunk Relative path: Specs/8/f/f/AMapFoundation/1.5.1/AMapFoundation.podspec.json exists! Returning local because checking is only perfomed in repo update
>       CDN: trunk Relative path: Specs/8/f/f/AMapFoundation/1.5.0/AMapFoundation.podspec.json exists! Returning local because checking is only perfomed in repo update
>       CDN: trunk Relative path: Specs/8/f/f/AMapFoundation/1.4.3/AMapFoundation.podspec.json exists! Returning local because checking is only perfomed in repo update
>       CDN: trunk Relative path: Specs/8/f/f/AMapFoundation/1.4.2/AMapFoundation.podspec.json exists! Returning local because checking is only perfomed in repo update
>       CDN: trunk Relative path: Specs/8/f/f/AMapFoundation/1.4.1/AMapFoundation.podspec.json exists! Returning local because checking is only perfomed in repo update
>       CDN: trunk Relative path: Specs/8/f/f/AMapFoundation/1.4.0/AMapFoundation.podspec.json exists! Returning local because checking is only perfomed in repo update
>       CDN: trunk Relative path: Specs/5/d/c/Mantle/2.1.0/Mantle.podspec.json exists! Returning local because checking is only perfomed in repo update
>       CDN: trunk Relative path: Specs/5/d/c/Mantle/2.1.0/Mantle.podspec.json exists! Returning local because checking is only perfomed in repo update
> 
>     Comparing resolved specification to the sandbox manifest
>       A AMapFoundation
>       A AMapLocation
>       A Flutter
>       A Mantle
>       A amap_core_fluttify
>       A amap_location_fluttify
>       A flutter_image_compress
>       A flutter_local_notifications
>       A foundation_fluttify
>       A image_picker
>       A permission_handler
>       A shared_preferences
>       A shared_preferences_macos
>       A shared_preferences_web
> 
>     Downloading dependencies
> 
>     -> Installing AMapFoundation (1.6.0)
>       > Copying AMapFoundation from `/Users/qg/Library/Caches/CocoaPods/Pods/Release/AMapFoundation/1.6.0-bc2f6` to `Pods/AMapFoundation`
> 
>     -> Installing AMapLocation (2.6.3)
>       > Copying AMapLocation from `/Users/qg/Library/Caches/CocoaPods/Pods/Release/AMapLocation/2.6.3-dc2c4` to `Pods/AMapLocation`
> 
>     -> Installing Flutter (1.0.0)
> 
>     -> Installing Mantle (2.1.0)
>       > Copying Mantle from `/Users/qg/Library/Caches/CocoaPods/Pods/Release/Mantle/2.1.0-2fa75` to `Pods/Mantle`
> 
>     -> Installing amap_core_fluttify (0.0.1)
> 
>     -> Installing amap_location_fluttify (0.0.1)
> 
>     -> Installing flutter_image_compress (0.0.1)
> 
>     -> Installing flutter_local_notifications (0.0.1)
> 
>     -> Installing foundation_fluttify (0.0.1)
> 
>     -> Installing image_picker (0.0.1)
> 
>     -> Installing permission_handler (4.0.0)
> 
>     -> Installing shared_preferences (0.0.1)
> 
>     -> Installing shared_preferences_macos (0.0.1)
> 
>     -> Installing shared_preferences_web (0.0.1)
>       - Running pre install hooks
>     [!] The 'Pods-Runner' target has transitive dependencies that include statically linked binaries: (/Users/qg/WorkSpace/git/noodle_flutter/ios/Pods/AMapFoundation/AMapFoundationKit.framework and /Users/qg/WorkSpace/git/noodle_flutter/ios/Pods/AMapLocation/AMapLocationKit.framework)
> 
>     /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/xcode/target_validator.rb:84:in `block (2 levels) in verify_no_static_framework_transitive_dependencies'
>     /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/xcode/target_validator.rb:74:in `each_key'
>     /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/xcode/target_validator.rb:74:in `block in verify_no_static_framework_transitive_dependencies'
>     /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/xcode/target_validator.rb:73:in `each'
>     /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/xcode/target_validator.rb:73:in `verify_no_static_framework_transitive_dependencies'
>     /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/xcode/target_validator.rb:38:in `validate!'
>     /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:590:in `validate_targets'
>     /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:158:in `install!'
>     /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/command/install.rb:52:in `run'
>     /Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
>     /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/command.rb:52:in `run'
>     /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/bin/pod:55:in `<top (required)>'
>     /usr/local/bin/pod:23:in `load'
>     /usr/local/bin/pod:23:in `<main>'
> 
> Error output from CocoaPods:
> ↳
> 
>     [!] Automatically assigning platform `iOS` with version `8.0` on target `Runner` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.
> 
> Finished with error: Error running pod install

插件版本改回0.7.0及以下就能解决

**flutter doctor**
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.15.2 19C57, locale zh-Hans-CN)
 
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
[✓] Android Studio (version 3.5)
[✓] IntelliJ IDEA Ultimate Edition (version 2019.2.4)
[✓] Connected device (2 available)

! Doctor found issues in 1 category.

**Comment by yohom** [comment]
解决方案：注释掉Podfile里的`use_framework!`，或者使用objc重新创建项目。
原因：0.8.0开始使用Pod远程依赖，高德提供的pod是静态库，而swift默认用的是动态库依赖。

**Comment by caocong1** [comment]
> 解决方案：注释掉Podfile里的`use_framework!`，或者使用objc重新创建项目。
> 原因：0.8.0�开始使用Pod远程依赖，高德提供的pod是静态库，而swift默认用的是动态库依赖。

多谢回答，现在注释`use_framework!`可以使用

**Comment by YDJSZY** [comment]
注释掉use_framework也不行

**Comment by cv0cv0** [comment]
这个问题应该怎么解决？

**Comment by cv0cv0** [comment]
@YDJSZY 你解决了吗？
