### ISSUE TITLE
[android] 没有定位结果

### ISSUE THREAD

**Issue by JakeWoki** [fluttify-project/amap_location_fluttify#44]
版本：0.8.3+4d92ce0

```
if (await requestPermission()) {
  print('=====');
  final location = await AmapLocation.fetchLocation();
  print('=====$location');
}
```

```
fluttify-dart: com.amap.api.location.AMapLocationClient@127123182::setLocationListener([])
fluttify-dart: com.amap.api.location.AMapLocationClientOption@136904591::setOnceLocation(['var1':true])
fluttify-dart: com.amap.api.location.AMapLocationClientOption@136904591::setLocationMode([])
fluttify-dart: com.amap.api.location.AMapLocationClientOption@136904591::setSensorEnable(['var1':true])
fluttify-dart: com.amap.api.location.AMapLocationClient@127123182::setLocationOption([])
fluttify-dart: com.amap.api.location.AMapLocationClient@127123182::startLocation([])
```
print('=====$location');没看到这个打印
没看到
`fluttify-dart-callback: onLocationChanged([])`
demo有上面这个打印

**Comment by JakeWoki** [comment]
断点com_amap_api_location_AMapLocationListener的onLocationChanged一直没有回调

**Comment by JakeWoki** [comment]
[ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference, null, null)
换旧的版本也不行，再换回最新0.8.3+4d92ce0后，直接报这个错了

**Comment by yohom** [comment]
@JakeWoki 你先下载demo apk试下能不能正常获取定位 https://github.com/fluttify-project/amap_location_fluttify/blob/master/example/build/app/outputs/apk/release/app-release.apk?raw=true

**Comment by JakeWoki** [comment]
demo apk可以获取到，直接运行demo也可以获取到

**Comment by yohom** [comment]
那应该就是key不对，建议多检查一下。

**Comment by JakeWoki** [comment]
如果是key有问题，会提示鉴权有问题的

**Comment by yohom** [comment]
那我也不知道了 :)

**Comment by kossfun** [comment]
俺也遇到这个问题, 高德地图后台 key sha1 packageName 检查过都是正确的, 控制台打印的日志也没有说是鉴权问题. 也是抛出这句 ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference, null, null)

俺 location map search 都引用了 就地图是可以正常用,  搜索和定位 都是报上面那句, 理论上说地图可以用,证明 key是正确的了吧?

**Comment by yohom** [comment]
```
ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference, null, null)
```
这个错可否贴一个完整一点的，具体在哪一行报的这个错？

**Comment by kossfun** [comment]
![图片](https://user-images.githubusercontent.com/49841387/71984455-d2eb2b80-3263-11ea-8608-70019ad90e76.png)

这是我点击定位后的所有报错信息了

E/flutter (14813): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference, null, null)
E/flutter (14813): #0      _IndexAppBarState.getLocation (package:travel_chat_flutter/ui/page/main/index_page.dart:67:25)
E/flutter (14813): <asynchronous suspension>
E/flutter (14813): #1      _IndexAppBarState.build.<anonymous closure> (package:travel_chat_flutter/ui/page/main/index_page.dart:92:19)
E/flutter (14813): #2      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:706:14)
E/flutter (14813): #3      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:789:36)
E/flutter (14813): #4      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
E/flutter (14813): #5      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:486:11)
E/flutter (14813): #6      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:264:5)
E/flutter (14813): #7      BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:199:7)
E/flutter (14813): #8      PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:467:9)
E/flutter (14813): #9      PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:76:12)
E/flutter (14813): #10     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:117:9)
E/flutter (14813): #11     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:379:8)
E/flutter (14813): #12     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:115:18)
E/flutter (14813): #13     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:101:7)
E/flutter (14813): #14     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:218:19)
E/flutter (14813): #15     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
E/flutter (14813): #16     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
E/flutter (14813): #17     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
E/flutter (14813): #18     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
E/flutter (14813): #19     _rootRunUnary (dart:async/zone.dart:1138:13)
E/flutter (14813): #20     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
E/flutter (14813): #21     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
E/flutter (14813): #22     _invoke1 (dart:ui/hooks.dart:273:10)
E/flutter (14813): #23     _dispatchPointerDataPacket (dart:ui/hooks.dart:182:5)

**Comment by kossfun** [comment]
> 
> 
> ```
> ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference, null, null)
> ```
> 
> 这个错可否贴一个完整一点的，具体在哪一行报的这个错？

我把项目代码上传了, 你看看
https://github.com/KossFun/flutter_map_demo

**Comment by yohom** [comment]
> > ```
> > ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference, null, null)
> > ```
> > 
> > 
> > 这个错可否贴一个完整一点的，具体在哪一行报的这个错？
> 
> 我把项目代码上传了, 你看看
> [KossFun/flutter_map_demo](https://github.com/KossFun/flutter_map_demo)

OK，我会抽时间看下，感谢反馈，我比较喜欢你这样的反馈，直接上能够复现问题的repo 😉

**Comment by yohom** [comment]
原因我查到了，跟新版android embedding有关，如果你只使用定位组件，那么可以先强制依赖foundation_fluttify为0.4.3版本试下，如果用到另外两个组件，那么可能也要降低一下版本，但是具体降到多少版本可能需要你自己试一下，这个问题我会找时间看下怎么处理。
```yaml
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  decorated_flutter: ^0.10.0
  amap_location_fluttify: ^0.8.5+107df19
  permission_handler: ^4.0.0

# 这里覆盖一下foundation_fluttify的版本
dependency_overrides:
  foundation_fluttify: 0.4.3

```

**Comment by JakeWoki** [comment]
按上面改用定位可以了。
新版android embedding
`FoundationFluttifyPlugin`
``` Kotlin
override fun onAttachedToEngine(binding: FlutterPlugin.FlutterPluginBinding) {
        val plugin = FoundationFluttifyPlugin()

        gMethodChannel = MethodChannel(binding.binaryMessenger, "com.fluttify/foundation_method")
        gMethodChannel.setMethodCallHandler(plugin)

        gBroadcastEventChannel = EventChannel(binding.binaryMessenger, "com.fluttify/foundation_broadcast_event")
    }
```
这里应该错了，去掉 `val plugin = FoundationFluttifyPlugin()`
`gMethodChannel.setMethodCallHandler(plugin)`改成`gMethodChannel.setMethodCallHandler(this)`

**Comment by yohom** [comment]
ok，我会尽快更新一下`foundation_fluttify`.

**Comment by yohom** [comment]
`foundation_fluttify` 0.4.5+1版本处理了这个问题，`flutter packages upgrade; flutter packages get`跑一下升级一下依赖。

**Comment by JakeWoki** [comment]
`foundation_fluttify` 0.4.5+1刚刚用了可以获取到结果了
