### ISSUE TITLE
0.8.3 Android编译错误

### ISSUE THREAD

**Issue by caocong1** [fluttify-project/amap_location_fluttify#45]
**插件版本**
0.8.3
**遇到bug的平台(Android/iOS)**
Android

**报错内容**

> 注: /Users/qg/.pub-cache/hosted/pub.flutter-io.cn/amap_location_fluttify-0.8.3+4d92ce0/android/src/main/java/me/yohom/amap_location_fluttify/AmapLocationFluttifyPlugin.java使用或覆盖了已过时的 API。
> 注: 有关详细信息, 请使用 -Xlint:deprecation 重新编译。
> 注: /Users/qg/.pub-cache/hosted/pub.flutter-io.cn/amap_location_fluttify-0.8.3+4d92ce0/android/src/main/java/me/yohom/amap_location_fluttify/AmapLocationFluttifyPlugin.java使用了未经检查或不安全的操作。
> 注: 有关详细信息, 请使用 -Xlint:unchecked 重新编译。
> D8: Program type already present: com.amap.api.fence.DistrictItem$1
> com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: 
> Program type already present: com.amap.api.fence.DistrictItem$1
> Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.
> 	at com.android.builder.dexing.D8DexArchiveMerger.getExceptionToRethrow(D8DexArchiveMerger.java:131)
> 	at com.android.builder.dexing.D8DexArchiveMerger.mergeDexArchives(D8DexArchiveMerger.java:118)
> 	at com.android.build.gradle.internal.transforms.DexMergerTransformCallable.call(DexMergerTransformCallable.java:102)
> 	at com.android.build.gradle.internal.tasks.DexMergingTaskRunnable.run(DexMergingTask.kt:444)
> 	at com.android.build.gradle.internal.tasks.Workers$ActionFacade.run(Workers.kt:335)
> 	at org.gradle.workers.internal.AdapterWorkAction.execute(AdapterWorkAction.java:50)
> 	at org.gradle.workers.internal.DefaultWorkerServer.execute(DefaultWorkerServer.java:47)
> 	at org.gradle.workers.internal.NoIsolationWorkerFactory$1$1$1.create(NoIsolationWorkerFactory.java:65)
> 	at org.gradle.workers.internal.NoIsolationWorkerFactory$1$1$1.create(NoIsolationWorkerFactory.java:61)
> 	at org.gradle.internal.classloader.ClassLoaderUtils.executeInClassloader(ClassLoaderUtils.java:98)
> 	at org.gradle.workers.internal.NoIsolationWorkerFactory$1$1.execute(NoIsolationWorkerFactory.java:61)
> 	at org.gradle.workers.internal.AbstractWorker$1.call(AbstractWorker.java:44)
> 	at org.gradle.workers.internal.AbstractWorker$1.call(AbstractWorker.java:41)
> 	at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:416)
> 	at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:406)
> 	at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
> 	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
> 	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
> 	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:102)
> 	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
> 	at org.gradle.workers.internal.AbstractWorker.executeWrappedInBuildOperation(AbstractWorker.java:41)
> 	at org.gradle.workers.internal.NoIsolationWorkerFactory$1.execute(NoIsolationWorkerFactory.java:56)
> 	at org.gradle.workers.internal.DefaultWorkerExecutor$3.call(DefaultWorkerExecutor.java:215)
> 	at org.gradle.workers.internal.DefaultWorkerExecutor$3.call(DefaultWorkerExecutor.java:210)
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 	at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.runExecution(DefaultConditionalExecutionQueue.java:215)
> 	at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.runBatch(DefaultConditionalExecutionQueue.java:164)
> 	at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.run(DefaultConditionalExecutionQueue.java:131)
> 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
> 	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> 	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
> 	at java.lang.Thread.run(Thread.java:748)
> Caused by: com.android.tools.r8.CompilationFailedException: Compilation failed to complete
> 	at com.android.tools.r8.utils.t.a(:55)
> 	at com.android.tools.r8.D8.run(:11)
> 	at com.android.builder.dexing.D8DexArchiveMerger.mergeDexArchives(D8DexArchiveMerger.java:116)
> 	... 34 more
> Caused by: com.android.tools.r8.utils.AbortException: Error: Program type already present: com.amap.api.fence.DistrictItem$1
> 	at com.android.tools.r8.utils.Reporter.a(:21)
> 	at com.android.tools.r8.utils.Reporter.a(:7)
> 	at com.android.tools.r8.utils.t.a(:36)
> 	... 36 more
> 
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':app:mergeExtDexDebug'.
> > A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
>    > com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: 
>      Program type already present: com.amap.api.fence.DistrictItem$1
>      Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 19s
> [!] The shrinker may have failed to optimize the Java bytecode.
>     To disable the shrinker, pass the `--no-shrink` flag to this command.
>     To learn more, see: https://developer.android.com/studio/build/shrink-code
> Finished with error: Gradle task assembleDebug failed with exit code 1
> 

**flutter doctor**

> Doctor summary (to see all details, run flutter doctor -v):
> [✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.15.2 19C57, locale zh-Hans-CN)
> [✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
> [✓] Xcode - develop for iOS and macOS (Xcode 11.3)
> [✓] Android Studio (version 3.5)
> [✓] IntelliJ IDEA Ultimate Edition (version 2019.3.1)
> [✓] Connected device (1 available)
> 
> • No issues found!
>

**Comment by xflcx1991** [comment]
升级到新版试试? 0.8.11 正常。但是依赖的 path_provider 会报类似的已过时的 API的警告，但可以运行，path_provider 项目有这个issue。
另外吐槽，本项目的example 中获取权限失败的`toast('需要定位权限!');`会导致错误，换一个toast项目才OK
