### ISSUE TITLE
华为机型，版本：0.8.5+107df19，稳定闪退

### ISSUE THREAD

**Issue by wbbbbbbbbbbbbbbbbbb** [fluttify-project/amap_location_fluttify#46]
**插件版本**
0.8.5+107df19
**遇到bug的平台(Android/iOS)**
Android
**描述bug**
其他机型暂时未发现问题
但是在测试了两台华为机型后
就会稳定出现闪退现象
机型：mate20-pro 和 荣耀P20
**复现步骤**
`
import 'package:amap_location_fluttify/amap_location_fluttify.dart';

.....

if (isIos) {
   await AmapCore.init(Config.AMAP_KEY);
}
_loc = await AmapLocation.fetchLocation();

// 猜测是中源码的这段闪退
// invoke native method
final result = await MethodChannel('me.yohom/amap_location_fluttify').invokeMethod('com.amap.api.location.AMapLocationClient::startLocation', {"refId": refId});
`

**flutter doctor**
`
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, v1.13.1-pre.94, on Microsoft Windows [Version 10.0.18362.535], locale
    zh-CN)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
[√] Android Studio (version 3.4)
[√] Connected device (1 available)

• No issues found!
`

**Comment by danieldai** [comment]
我用0.8.6+356f11c在华为手机上倒是不闪退，但是不能获取到经纬度数据，相同的代码在另一个android手机上可以获取到经纬度

**Comment by wbbbbbbbbbbbbbbbbbb** [comment]
> 我用0.8.6+356f11c在华为手机上倒是不闪退，但是不能获取到经纬度数据，相同的代码在另一个android手机上可以获取到经纬度

我已经换了百度地图的包了，你也可以试试，暂时没大问题

**Comment by tec8297729** [comment]
我也碰到闪退情况，在小米10真机上面，打包release版本，加入了官方的混淆规则minifyEnabled true，打开APP只要调用了定位就闪退！！！

**Comment by yohom** [comment]
上下奔溃日志。

**Comment by wva37254626** [comment]
我也遇到了这样的问题,华为P20和荣耀8青春版,华为系的都存在崩溃问题,在小米8,vivoY7s其他品牌都不存在问题
[Bugly - 崩溃日志.pdf](https://github.com/fluttify-project/amap_location_fluttify/files/4330194/Bugly.-.pdf)
