### ISSUE TITLE
小米6无法正常调用

### ISSUE THREAD

**Issue by zhiwei007** [fluttify-project/amap_location_fluttify#47]
**插件版本**
amap_location_fluttify: ^0.8.5+107df19
 

**描述bug**

  ] I/flutter (27059): ========getLocation start===================
[  +34 ms] D/ObjectFactory(27059): 创建对象: com_amap_api_location_AMapLocationClient__android_content_Context
[        ] W/System.err(27059): java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
[  +33 ms] W/System.err(27059): 	at me.yohom.amap_location_fluttify.AmapLocationFluttifyPlugin$1.lambda$new$272(AmapLocationFluttifyPlugin.java:8756)
[        ] W/System.err(27059): 	at me.yohom.amap_location_fluttify.-$$Lambda$AmapLocationFluttifyPlugin$1$JE00UKpZAISm0a68U9a4vf_Hd04.call(Unknown Source:0)
[        ] W/System.err(27059): 	at me.yohom.amap_location_fluttify.AmapLocationFluttifyPlugin.onMethodCall(AmapLocationFluttifyPlugin.java:9074)
[        ] W/System.err(27059): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:231)
[        ] W/System.err(27059): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:93)
[        ] W/System.err(27059): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:642)
[        ] W/System.err(27059): 	at android.os.MessageQueue.nativePollOnce(Native Method)
[        ] W/System.err(27059): 	at android.os.MessageQueue.next(MessageQueue.java:332)
[        ] W/System.err(27059): 	at android.os.Looper.loop(Looper.java:168)
[        ] W/System.err(27059): 	at android.app.ActivityThread.main(ActivityThread.java:6878)
[        ] W/System.err(27059): 	at java.lang.reflect.Method.invoke(Native Method)
[        ] W/System.err(27059): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
[        ] W/System.err(27059): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:876)
[        ] I/flutter (27059): get location cause exception::::::PlatformException(Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference, null, null)

**Comment by yohom** [comment]
参考 #44 。
