### ISSUE TITLE
await location.city 获取城市 崩溃了；

### ISSUE THREAD

**Issue by Tom-Jack-Huang** [fluttify-project/amap_location_fluttify#49]
版本 0.8.6 

*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff23c7127e __exceptionPreprocess + 350
	1   libobjc.A.dylib                     0x00007fff513fbb20 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff23c91fd4 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   CoreFoundation                      0x00007fff23c75c4c ___forwarding___ + 1436
	4   CoreFoundation                      0x00007fff23c77f78 _CF_forwarding_prep_0 + 120
	5   Runner                              0x00000001008153e7 __61-[AmapLocationFluttifyPlugin initWithFlutterPluginRegistrar:]_block_invoke_45 + 263
	6   Runner                              0x000000010082368a -[AmapLocationFluttifyPlugin handleMethodCall:result:] + 346
	7   Flutter                             0x0000000100e34f95 __45-[FlutterMethodChannel setM<…>

**Comment by EaglesChen** [comment]
同样错误在ios虚拟机上，真机没有崩溃过。

**Comment by RockerFlower** [comment]
iOS 模拟器崩溃。
