### ISSUE TITLE
ios  编译失败 有了这个模块 各种模块冲突

### ISSUE THREAD

**Issue by srcker** [fluttify-project/amap_location_fluttify#52]
'AMapFoundation' uses the unencrypted 'http' protocol to transfer the
    Pod. Please be sure you're in a safe network with only trusted hosts.
    Otherwise, please reach out to the library author to notify them of this
    security issue.

**Comment by yohom** [comment]
> 'AMapFoundation' uses the unencrypted 'http' protocol to transfer the
> Pod. Please be sure you're in a safe network with only trusted hosts.
> Otherwise, please reach out to the library author to notify them of this
> security issue.

有道翻译：
> “AMapFoundation”使用未加密的“http”协议来传输
> 豆荚(Pod)。请确保您的网络是安全的，只有可信任的主机。
> 否则，请联系图书馆(library)的作者，告诉他们这一点
> 安全问题。

应该是cocoapods的问题，跟flutter没有直接关系。
