### ISSUE TITLE
下载了你的这个amap_locationAPP后效果是一样的，你可以验证下华为手机P30 系统是10 二次定位数据没返回，失败

### ISSUE THREAD

**Issue by zhuimengHCZ** [fluttify-project/amap_location_fluttify#53]
下载了你的这个amap_locationAPP后效果是一样的，你可以验证下华为手机P30 系统是10
[√] Flutter (Channel stable, v1.12.13+hotfix.8, on Microsoft Windows [Version 10.0.18362.657], locale zh-CN)
    • Flutter version 1.12.13+hotfix.8 at D:\Xin\flutter
    • Framework revision 0b8abb4724 (3 weeks ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at D:\Xin\AndroidSdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • ANDROID_HOME = D:\Xin\AndroidSdk
    • Java binary at: D:\Xin\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[!] Android Studio (version 2.2)
    • Android Studio at D:\Xin\AndroidStudio2.2.3\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_76-release-b03)

[√] Android Studio (version 3.6)
    • Android Studio at D:\Xin\Android Studio
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] Connected device (1 available)
    • ELE AL00 • 8KE5T19301003594 • android-arm64 • Android 10 (API 29)
environment:
  sdk: ">=2.3.0 <3.0.0"
#定位
  amap_location_fluttify: ^0.8.7+1053dca

主页
void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await enableFluttifyLog(true); // 关闭log
  await AmapService.init(iosKey: 'id',androidKey: 'id');
  runApp(new MyApp());
}
定位页
initLocation() async {
    final location = await AmapLocation.fetchLocation(
        needAddress: true, mode: LocationAccuracy.High);
    if (location != null && (await location.latLng) != null) {
      address = await location.address;
      await location.latLng.then((it) {
        setState(() {
          longitude = it.longitude;
          latitude = it.latitude;
        });
      });
    }
 }
然后关闭app到桌面后提示“EGLNativeWindowType 0x7d5d9c2010 disconnect failed” 
之后再进入定位页
initLocation() async {
    final location = await AmapLocation.fetchLocation(
        needAddress: true, mode: LocationAccuracy.High);
    if (location != null && (await location.latLng) != null) {
      address = await location.address;
      await location.latLng.then((it) {
        setState(() {
          longitude = it.longitude;
          latitude = it.latitude;
        });
      });
    }
 }
这里返回的经纬度和地址为空

我加了AmapLocationDisposeMixin后，
fluttify-java: com.amap.api.location.AMapLocationClient@114144016::onDestroy()
W/System.err(14882): java.lang.NullPointerException: Attempt to invoke virtual method 'void com.amap.api.location.AMapLocationClient.onDestroy()' on a null object reference

**Comment by yohom** [comment]
我google了一下，看上去像是flutter的bug
参考
https://github.com/flutter/flutter/issues/29757
https://github.com/flutter/flutter/issues/28651

**Comment by yohom** [comment]
发现问题了，是插件的bug，更新了0.8.10版本，应该可以了，你试下。
