### ISSUE TITLE
能否彻底关闭console的日志

### ISSUE THREAD

**Issue by xflcx1991** [fluttify-project/amap_location_fluttify#55]
**功能描述**
翻 doc 网站发现`enableFluttifyLog(false)` 可以关闭日志，实际测试后确实有效果，但是还是有部分日志，比如
> D/ObjectFactory(14260): 创建对象: com_amap_api_location_AMapLocationClient__android_content_Context
D/ObjectFactory(14260): 创建对象: com_amap_api_location_AMapLocationClientOption__
D/NetworkSecurityConfig(14260): No Network Security Config specified, using platform default

不清楚第三行是不是本项目的输出，但是前两行肯定是。不过我全文件夹搜索「创建对象」也没找到那个代码里有对应的输出，所以找不下去了。请问能否关闭这些输出。

**Comment by yohom** [comment]
这应该是漏掉了，你可以确认下还有其他类似的漏关掉的日志吗，我一起改下。

**Comment by xflcx1991** [comment]
我用example项目，添加了关闭日志代码后
>   runApp(MyApp());
  await enableFluttifyLog(false);

把「单次定位」、「连续定位」、「停止定位」都依次点过后的全部日志在这里：
`https://gist.github.com/xflcx1991/3773857fbbcdc7ee5068becabaa3e877`

**Comment by yohom** [comment]
ok, 下个版本处理一下这个问题。
