### ISSUE TITLE
安卓定位为空

### ISSUE THREAD

**Issue by a642815311** [fluttify-project/amap_location_fluttify#57]
**插件版本**
amap_location_fluttify: ^0.8.11+481e45c
**遇到bug的平台(Android/iOS)**
安卓无法返回定位信息，检查过key和sha1是正确的，原来是可以定到位的
**描述bug**
![image](https://user-images.githubusercontent.com/37214176/76594033-e69c6200-6532-11ea-8e45-ef1f6cf32910.png)
**复现步骤**
我使用了另一个插件，那个插件需要插入混淆，我加入了混淆代码，导致安卓定位的定位信息为空
**期望行为**
解决方法
**截图**
![image](https://user-images.githubusercontent.com/37214176/76594115-28c5a380-6533-11ea-9be8-404dd1a84cdf.png)

**flutter doctor**
![image](https://user-images.githubusercontent.com/37214176/76594134-3713bf80-6533-11ea-977c-6c4a9cdaa722.png)

**Comment by a642815311** [comment]
我另外加入高德地图的混淆也不行
-dontwarn com.amap.**
-keep class com.amap.api.location.** { *; }
-keep class com.amap.api.fence.** { *; }
-keep class com.autonavi.aps.amapapi.model.** { *; }
-keep class com.amap.api.maps.model.** { *; }

**Comment by hzp1993** [comment]
同样 原来的可以升级了插件获取不到地区
