### ISSUE TITLE
关于后台持续/间隔定位（Android+iOS）

### ISSUE THREAD

**Issue by 62218** [fluttify-project/amap_location_fluttify#58]
**功能描述**

麻烦大佬两分钟看看此issue。

需求/场景：在后台（返回桌面甚至退出app，锁屏等）仍然可以进行定位，比如用于收集定位信息形成轨迹展示（车辆/外卖/服务人员行程）。

-  Android端必然涉及到service吧，高德demo开启一个前台进程（https://github.com/amap-demo/android-o-backgroundlocation）。
   另外Android应该也需要处理保活吧哈哈哈好头痛。
-  iOS原生开发我不懂，不过听说设置个属性授权一下就可以实现后台定位

看了此插件貌似仅适用于单次定位，比如退出页面就无法定位？还有就是ios如果本身支持后台定位，是否直接在flutter的main函数里直接调用此插件的定位方式回调后台持续定位信息实现此需求，当然Android是无法直接的吧？应该要处理service。

如果有方案/思路，可否大概指点指点？ 
如果实现有难度/时间，我可以重新开一个【技术支持的】issue，来处理此问题。

**Native端对应字段/方法**
Android：
1. https://lbs.amap.com/api/android-location-sdk/guide/utilities/permision_8
2. https://github.com/amap-demo/android-o-backgroundlocation

iOS：
1. https://lbs.amap.com/api/ios-location-sdk/guide/get-location/backgroundlocation

**Comment by yohom** [comment]
我先调查一下，如果可以做的话就转技术支持工单吧。

**Comment by yohom** [comment]
我做了一些调查，调用高德SDK本身的后台定位接口其实问题是不大的，比较棘手的是后台运行dart代码，因为你退出app后，flutter引擎就已经detach了，没有运行dart的环境了，就算原生代码还在不停的获取定位，你是无法利用这些原生回调来执行你的dart代码的。
所以需要引入后台运行dart的机制，我查了一些资料，目前看来都还比较复杂，我还需要再花写时间深入了解下后台运行dart的方式。
参考资料:
1. https://medium.com/flutter/executing-dart-in-the-background-with-flutter-plugins-and-geofencing-2b3e40a1a124
2. https://github.com/transistorsoft/flutter_background_fetch
3. https://github.com/flutter/flutter/issues/32164
4. https://github.com/flutter/plugins/tree/master/packages/android_alarm_manager
