### ISSUE TITLE
要在iOS 11及以上版本使用后台定位服务, 需要实现amapLocationManager:doRequireLocationAuth: 代理方法

### ISSUE THREAD

**Issue by stack-info** [fluttify-project/amap_location_fluttify#6]
**插件版本**
0.2.5
**描述bug**
fluttify-objc: AMapLocationManager@105553150849024::requestLocationWithReGeocode(暂未实现参数打印)
[AMapLocationKit] 要在iOS 11及以上版本使用后台定位服务, 需要实现amapLocationManager:doRequireLocationAuth: 代理方法

**Comment by yohom** [comment]
@syncio 可否提供一下复现步骤？

**Comment by yohom** [comment]
@syncio `0.2.7`版本，已经添加`requireAlwaysAuth`方法，可以在需要的地方调用这个方法申请后台定位权限。

**Comment by feicong666** [comment]
我的也出现了这个问题，调用requireAlwaysAuth之后 还是出现报错

调用：
   try {
      AmapLocation.requireAlwaysAuth().then((data){
        Timer.periodic(Duration(milliseconds: 30000), (t){
          getLocation();
        });
      });
   } catch(error) {}

报错：
flutter: Overflow on channel: flutter/lifecycle.  Messages on this channel are being discarded in FIFO fashion.  The engine may not be running or you need to adjust the buffer size if of the channel.
flutter: fluttify-dart: AMapServices::sharedServices([])
[VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: NoSuchMethodError: The method 'set_delegate' was called on null.
Receiver: null
Tried calling: set_delegate(Instance of '_IOSLocationDelegate')
#0      Object.noSuchMethod  (dart:core-patch/object_patch.dart:51:5)
#1      AmapLocation.requireAlwaysAuth.<anonymous closure> 
package:amap_location_fluttify/…/dart/amap_location.dart:146
<asynchronous suspension>
#2      platform 
package:foundation_fluttify/…/function/functions.dart:44
<asynchronous suspension>
#3      AmapLocation.requireAlwaysAuth 
package:amap_location_fluttify/…/dart/amap_location.dart:140
#4      _MainWebviewFWPState.initState 
package:flutter_gr/main-webview-fwp.dart:64
#5      StatefulElement._firstBuild 
package:flutter/…/widgets/framework.dart:4085
#6      ComponentElement.mount 
package:flutter/…/widgets/framework.dart:3936
#7      Element.inflateWidget 
package:flutter/…/widgets/framework.dart:3109
#8      Element.updateChild (package:<…>

**Comment by feicong666** [comment]
@yohom 麻烦作者看看呢

**Comment by mzF414** [comment]
requireAlwaysAuth 可否把这个方法的调用也加到demo中呢? @yohom
