### ISSUE TITLE
fetchLocation中timeout参数的功能和单位不明确

### ISSUE THREAD

**Issue by s4turnight** [fluttify-project/amap_location_fluttify#61]
版本: ^0.10.0+e74b91b
```
例如
await AmapLocation.fetchLocation(mode: LocationAccuracy.HIGH, needAddress: true, timeout: 5);
```
* 在IOS端，貌似是会返回5秒钟内可以得到的最精确的定位结果（看了眼高德的文档）
* 但是在android，log会直接报https请求超时5ms，**注意不是5秒**

没有文档说明，不确定是不是issue

谢谢作者提供插件，试了一大圈，才找到一个能用的，已支持

**Comment by seanliang** [comment]
可以确认是个bug。因为，com.amap.api.location.AMapLocationClientOption.setHttpTimeOut参数是毫秒，但是调用时传递的是秒，如果设置为5秒就会瞬间超时。
