### ISSUE TITLE
在flutter master 最新的的版本下编译错误

### ISSUE THREAD

**Issue by aohanhe** [fluttify-project/amap_location_fluttify#62]
AILURE: Build failed with an exception. 
* What went wrong: 
Execution failed for task ':amap_location_fluttify:generateDebugRFile'. > java.util.NoSuchElementException (no error message) 
* Try: 
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights. 
* Get more help at https://help.gradle.org 
BUILD FAILED in 1m 41s

我们的项目因为遇到了在新的xcode 版本下不能正常工作的问题，所以没有办法切到了flutter master 版本。今天我的同事升级了最新的版本，结果项目就无法编译通过了。请问有没有什么解决办法

**Comment by shichunlei** [comment]
遇到同样的问题

**flutter doctor**
[✓] Flutter (Channel beta, v1.17.0, on Mac OS X 10.14.6 18G103, locale zh-Hans-CN)
    • Flutter version 1.17.0 at /Users/14cells/Android/flutter
    • Framework revision e6b34c2b5c (9 days ago), 2020-05-02 11:39:18 -0700
    • Engine revision 540786dd51
    • Dart version 2.8.1

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/14cells/Android/SDK
    • Platform android-R, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2.1, Build version 11B500
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)



**BUG**
```
Launching lib/main.dart on MI 5X in debug mode...
Running Gradle task 'assembleDebug'...

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':amap_core_fluttify:generateDebugRFile'.
> Could not resolve all task dependencies for configuration ':amap_core_fluttify:debugRuntimeClasspath'.
   > Could not resolve io.flutter:flutter_embedding_debug:1.0.0-540786dd51f112885a89792d678296b95e6622e5.
     Required by:
         project :amap_core_fluttify
         project :amap_core_fluttify > project :foundation_fluttify
      > Could not resolve io.flutter:flutter_embedding_debug:1.0.0-540786dd51f112885a89792d678296b95e6622e5.
         > Could not get resource 'https://storage.googleapis.com/download.flutter.io/io/flutter/flutter_embedding_debug/1.0.0-540786dd51f112885a89792d678296b95e6622e5/flutter_embedding_debug-1.0.0-540786dd51f112885a89792d678296b95e6622e5.pom'.
            > Could not HEAD 'https://storage.googleapis.com/download.flutter.io/io/flutter/flutter_embedding_debug/1.0.0-540786dd51f112885a89792d678296b95e6622e5/flutter_embedding_debug-1.0.0-540786dd51f112885a89792d678296b95e6622e5.pom'.
               > Connect to storage.googleapis.com:443 [storage.googleapis.com/172.217.160.80] failed: connect timed out

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 56s
Exception: Gradle task assembleDebug failed with exit code 1
```

**Comment by shichunlei** [comment]
这个问题应该不是插件的锅，应该是flutter的锅。

[看是否能解决你遇到的问题](https://github.com/shichunlei/flutter_app/issues/29)
