### ISSUE TITLE
本地运行真机无问题，打包发布后测试定位变为(0, 0)

### ISSUE THREAD

**Issue by JiaweiUTSCHINA** [fluttify-project/amap_location_fluttify#70]
**插件版本**
0.12.0
**遇到bug的平台(Android/iOS)**
Android
**描述bug**
手机接线flutter run的时候定位完全没问题，打包发布安装后使用获取到的经纬度变成了(0, 0)
**复现步骤**
配合amap_map_fluttify一起使用，amap_location_fluttify获取latlng后跳转页面，作为amap_map_fluttify的centerCoordinate使用。flutter run时定位很精准，说明不是apikey的问题。但是一打包就不好使。
**期望行为**
打包发布后能维持。
**截图**

**flutter doctor**
[√] Flutter (Channel stable, v1.17.1, on Microsoft Windows [Version 10.0.18363.836], locale zh-CN)
    • Flutter version 1.17.1 at C:\Flutter\flutter
    • Framework revision f7a6a7906b (2 weeks ago), 2020-05-12 18:39:00 -0700
    • Engine revision 6bc433c6b6
    • Dart version 2.8.2

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\tommy\AppData\Local\Android\Sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\AndroidStudio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at C:\AndroidStudio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] Connected device (1 available)
    • EML AL00 • CLB0218510003379 • android-arm64 • Android 10 (API 29)

• No issues found!

**Comment by yohom** [comment]
有可能是你release的sha1没有配对。
