### ISSUE TITLE
安卓定位返回0,0

### ISSUE THREAD

**Issue by 244226077** [fluttify-project/amap_location_fluttify#74]
同时用了amap search和amap location，前者正常说明key是没问题的，后者定位时返回了0,0。这是什么原因如何解决？

**Comment by 244226077** [comment]
新建一个工程，把代码拷贝进去运行就正常了，但是一段时间后偶尔还会出现这种情况，又得同样处理，如何才能一劳永逸？

**Comment by huangsir0** [comment]
亲解决了吗，我IOS正常，Android获取到的值都是0，0。初始值。

**Comment by kossfun** [comment]
检查一下有没有打开gps开关(开启位置服务)
