### ISSUE TITLE
鉴权错误信息

### ISSUE THREAD

**Issue by devkou** [fluttify-project/amap_location_fluttify#9]
**插件版本**
version: "0.2.1+38df15a"
**描述bug**
SHA1 和包名都对的 安卓上面跑提示说鉴权错误，大佬怎么回事呢？
**复现步骤**

**期望行为**

**截图**
AndroidManifest中的设置这个就行了吧？

        <meta-data
            android:name="我的包名=高德地图应用包名"
            android:value="高德地图appkey"/>

**flutter doctor**

**Comment by yohom** [comment]
@devkou 这个，鉴权信息错误那就是真的是鉴权信息错误哈，建议去高德官方论坛上看看。你的`<meta-data>`有配置在`<application>`标签下吗(正确)？还是配置到`<activity>`下了(错误)？
