### ISSUE TITLE
内存泄漏

### ISSUE THREAD

**Issue by wlhjkl** [fluttify-project/amap_location_fluttify#96]
**插件版本**
^0.20.0

**遇到bug的平台(Android/iOS)**
Android

**描述bug**
内存泄漏

**复现步骤**
无需复现，必现

**期望行为**
解注册下广播

**截图**

![image](https://user-images.githubusercontent.com/4336142/99081631-163dc580-25fe-11eb-8f3b-870807a0e739.png)

![image](https://user-images.githubusercontent.com/4336142/99081563-fa3a2400-25fd-11eb-90e6-d1392f03de5c.png)

**flutter doctor**
无关

**Comment by wanglu1209** [comment]
怎么解决的？
