### ISSUE TITLE
ios 定位无位置信息，仅经纬度

### ISSUE THREAD

**Issue by lmr520** [fluttify-project/amap_location_fluttify#97]
**插件版本**
 amap_location_fluttify: ^0.2.7+d2eb645

**遇到bug的平台(Android/iOS)**
ios

**描述bug**
AmapLocation.startLocation(
        once: true,
        needAddress: true,
        mode: LocationAccuracy.Low,
        locationChanged: (location)
仅获取到经纬度，无具体address

**复现步骤**

**期望行为**

**截图**

**flutter doctor**
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel unknown, 1.22.1, on Mac OS X 10.15.7 19H2, locale
    zh-Hans-CN)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
[✓] Android Studio (version 4.0)
[!] IntelliJ IDEA Ultimate Edition (version 2019.3.4)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.51.1)
[✓] Connected device (2 available)
    ! Error: iPhone is busy: Copying cache files from device. Xcode will
      continue when iPhone is finished. (code -10)

! Doctor found issues in 1 category.

**Comment by Yi-FanYan** [comment]
> **插件版本**
> amap_location_fluttify：^ 0.2.7 + d2eb645
> 
> **遇到bug的平台（Android / iOS）**
> ios
> 
> **描述错误**
> AmapLocation.startLocation（
> 一次：true，
> needAddress：true，
> 模式：LocationAccuracy.Low，
> locationChanged：（位置）仅
> 获取到经纬度，无具体地址
> 
> **复现步骤**
> 
> **期望行为**
> 
> **截图**
> 
> **flutter doctor**
> 医生摘要（要查看所有详细信息，请运行flutter doctor -v）：
> [✓] Flutter（通道未知，1.22.1，在Mac OS X 10.15.7 19H2上，语言环境
> zh-Hans-CN）
> 
> [✓] Android工具链-为Android设备开发（Android SDK版本30.0.0）
> [✓] Xcode-为iOS和macOS开发（Xcode 12.2）
> [✓] Android Studio（版本4.0）
> [！] IntelliJ IDEA Ultimate Edition（版本） 2019.3.4）
> not未安装Flutter插件; 这增加了Flutter的特定功能。
> art未安装Dart插件；这增加了Dart特定的功能。
> [✓] VS代码（1.51.1版）
> [✓]已连接设备（2个可用）
> ！错误：iPhone忙：从设备复制缓存文件。
> iPhone完成后，Xcode将继续。（代码-10）
> 
> ！医生发现了1类问题。

请在高德地图看看你的key 和你在调用init的key是不是同一个

**Comment by Yi-FanYan** [comment]
> **插件版本**
> amap_location_fluttify：^ 0.2.7 + d2eb645
> 
> **遇到bug的平台（Android / iOS）**
> ios
> 
> **描述错误**
> AmapLocation.startLocation（
> 一次：true，
> needAddress：true，
> 模式：LocationAccuracy.Low，
> locationChanged：（位置）仅
> 获取到经纬度，无具体地址
> 
> **复现步骤**
> 
> **期望行为**
> 
> **截图**
> 
> **flutter doctor**
> 医生摘要（要查看所有详细信息，请运行flutter doctor -v）：
> [✓] Flutter（通道未知，1.22.1，在Mac OS X 10.15.7 19H2上，语言环境
> zh-Hans-CN）
> 
> [✓] Android工具链-为Android设备开发（Android SDK版本30.0.0）
> [✓] Xcode-为iOS和macOS开发（Xcode 12.2）
> [✓] Android Studio（版本4.0）
> [！] IntelliJ IDEA Ultimate Edition（版本） 2019.3.4）
> not未安装Flutter插件; 这增加了Flutter的特定功能。
> art未安装Dart插件；这增加了Dart特定的功能。
> [✓] VS代码（1.51.1版）
> [✓]已连接设备（2个可用）
> ！错误：iPhone忙：从设备复制缓存文件。
> iPhone完成后，Xcode将继续。（代码-10）
> 
> ！医生发现了1类问题。

ios也需要单独申请一个key 不然拿不到位置信息

**Comment by lmr520** [comment]
//初始化store
    await Application.initSp();
    await NetUtils.init();
    if (Platform.isIOS) {
      await AmapCore.init('9XXXXXXXXXXa');
      //ios相关代码

    }
    //初始化数据库
    if (Application.db == null) {
      await Application.initDb();
    }
    //初始化文件目录
    Application.sp.setString("appUrl", await FileUtil.localPath(true));


已确认有init key 且与高德上一致

**Comment by lmr520** [comment]
好像是ios Bundle ID 不一致
