### ISSUE TITLE
Are you missing a call to unregisterReceiver()?

### ISSUE THREAD

**Issue by liuweichn** [fluttify-project/amap_location_fluttify#99]
Activity com.xxx.MainActivity has leaked IntentReceiver me.yohom.amap_location_fluttify.sub_handler.custom.SubHandlerCustom$1@91c2141 that was originally registered here. Are you missing a call to unregisterReceiver()?

**Comment by akuanooo** [comment]
AmapLocation.instance.dispose(); 
before u exit app
